version: '3.8'

services:
  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: docker-redis
    labels:
      name: redis
      mode: standalone
    ports:
      - "6379:6379"
    networks:
      - app-net

  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-docker
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Set the active profile; adjust as necessary
    networks:
      - app-net

networks:
  app-net:

