version: '3.8'

services:
  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: docker-redis
    labels:
      name: redis
      mode: standalone
    ports:
      - "6379:6379"
    networks:
      - app-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  app:
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-docker
    environment:
#      - SPRING_PROFILES_ACTIVE=prod  # Set the active profile; adjust as necessary
        SPRING_DATASOURCE_URL : ${MYSQL_URL}
        SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_PW}
    networks:
      - app-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
networks:
  app-net:

