version: '3'
services:
  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - test_network
  application:
    container_name: drm-server
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://223.130.163.37:3306/drm
      SPRING_DATASOURCE_USERNAME: "keum2023"
      SPRING_DATASOURCE_PASSWORD: "keum2023!"
    depends_on:
      - redis-docker
    networks:
      - test_network

networks:
  test_network:
